version: 2.1
parameters:
  source_path:
    type: string
    default: '~/creme_crm'
  instance_directory:
    type: string
    default: 'creme_project'

commands:
  wait-database:
    description: Wait for the database
    parameters:
      port:
        type: integer
    steps:
      - run: dockerize -wait tcp://localhost:<< parameters.port >> -timeout 1m

  checkout-creme:
    description: Retrieve the Creme's source
    steps:
      - checkout:
          path: << pipeline.parameters.source_path >>

  install-creme-system-packages:
    description: Install creme dependencies
    steps:
      - run: sudo apt update
      - run: sudo apt install -y python3-dev graphviz libgraphviz-dev pkg-config lcab

  install-py-dev-env:
    parameters:
      python:
        type: string
    steps:
      - restore_cache:
          keys:
#            - <<parameters.python>>-creme_crm-{{ checksum "setup.cfg" }}
            - << parameters.python >>-creme_crm-{{ checksum "<< pipeline.parameters.source_path >>/setup.cfg" }}
            - << parameters.python >>-creme_crm

      - run: <<parameters.python>> -m venv ~/venv
      # Require setuptools v46.4.0 at least
      - run: ~/venv/bin/pip install -U pip setuptools
      - run: echo "source ~/venv/bin/activate" >> $BASH_ENV
#      - run: pip install -U -e .[dev,mysql,pgsql,graphs]
      - run: pip install -U -e << pipeline.parameters.source_path >>[dev,mysql,pgsql,graphs]
      - run: python --version
      - run: pip freeze
      - run: pip list --outdated

      - save_cache:
#          key: <<parameters.python>>-creme_crm-{{ checksum "setup.cfg" }}
          key: << parameters.python >>-creme_crm-{{ checksum "<< pipeline.parameters.source_path >>/setup.cfg" }}
          paths: "~/venv"

  install-node-env:
    steps:
      - restore_cache:
          key: node-dependencies-{{ checksum "<< pipeline.parameters.source_path >>/package-lock.json" }}

      - run: cp << pipeline.parameters.source_path >>/package*.json << pipeline.parameters.instance_directory >>
      - run:
          name: Installing NodeJS
          working_directory: << pipeline.parameters.instance_directory >>
          command: npm install && npm run eslint-install
          environment:
            ESLINT_CREME_PLUGINS: "<< pipeline.parameters.source_path >>/creme/static/utils/eslint/"
      - run:
          working_directory: << pipeline.parameters.instance_directory >>
          command: npm list

      - save_cache:
          key: node-dependencies-{{ checksum "<< pipeline.parameters.source_path >>/package-lock.json" }}
          paths:
            - << pipeline.parameters.instance_directory >>/node_modules

  create-creme-project:
    description: Create Creme project
    steps:
      - run: mkdir << pipeline.parameters.instance_directory >>
      - run: touch << pipeline.parameters.instance_directory >>/__init__.py
      - run: mkdir << pipeline.parameters.instance_directory >>/media
      - run: mkdir << pipeline.parameters.instance_directory >>/media/static
      # Not really useful because unit tests override with a sub-folder in /tmp/
      - run: mkdir << pipeline.parameters.instance_directory >>/media/upload
      - run: cp << pipeline.parameters.source_path >>/.circleci/circleci_settings.py << pipeline.parameters.instance_directory >>/settings.py

  setup-creme-statics:
    description: Setup Creme static resources
    steps:
      - run: creme generatemedia --settings=<< pipeline.parameters.instance_directory >>.settings

  setup-creme-unit-tests:
    description: Setup Creme database
    parameters:
      local_settings:
        type: string
        default: 'sqlite3_settings'
    steps:
      - run: cp << pipeline.parameters.source_path >>/.circleci/<< parameters.local_settings >>.py << pipeline.parameters.instance_directory >>/local_settings.py
      - run: creme migrate --settings=<< pipeline.parameters.instance_directory >>.settings
      - run: creme creme_populate --settings=<< pipeline.parameters.instance_directory >>.settings
      - run: creme generatemedia --settings=<< pipeline.parameters.instance_directory >>.settings

  run-creme-unit-tests:
    description: Run Creme unit tests
    steps:
      # File .coveragerc is implicitly used by coverage.py (use argument "--rcfile" instead?)
      - run: cp << pipeline.parameters.source_path >>/.circleci/circleci_coverage.ini .coveragerc
      - run: COVERAGE_PROCESS_START=.coveragerc coverage run --source << pipeline.parameters.source_path >>/creme/ << pipeline.parameters.source_path >>/creme/manage.py test --settings=<< pipeline.parameters.instance_directory >>.settings --noinput --parallel=8 creme
      - run: coverage combine
      - run: coverage html
      - store_artifacts:
          # NB: see .circleci/circleci_coverage.ini
          path: artifacts/coverage_html

  setup-locale:
    description: "Locale: Setup"
    parameters:
      language:
        type: string
      encoding:
        type: string
    steps:
      - run:
          name: "Locale: locale-gen"
          command: |
            echo "<< parameters.language >>.<< parameters.encoding >> << parameters.encoding >>" | sudo tee -a /etc/locale.gen
            sudo locale-gen
      - run:
          name: "Locale: Setup Environment Variables"
          command: |
            echo "export LANG=<< parameters.language >>.<< parameters.encoding >>" >> $BASH_ENV
            echo "export LANGUAGE=<< parameters.language >>" >> $BASH_ENV
            echo "export LC_ALL=<< parameters.language >>.<< parameters.encoding >>" >> $BASH_ENV


jobs:
  fast-fix:
    docker:
      - image: circleci/python:3.6-browsers
    resource_class: large
    steps:
      - checkout-creme
      - setup-locale:
          language: fr_FR
          encoding: UTF-8
      - install-creme-system-packages
      - install-py-dev-env:
          python: "python3.6"
      - create-creme-project
      - setup-creme-unit-tests
      - run: creme test creme.mobile.tests.test_activities.MobileActivitiesTestCase.test_activities_portal01 --settings=<< pipeline.parameters.instance_directory >>.settings --noinput

workflows:
  version: 2
  build:
    jobs:
      - fast-fix
